language: python
python:
  - 2.7
  - 3.6

matrix:
  include:
    - python: 3.6
      install: pip install flake8
      script: flake8 **/*.py
install:
  - pip install pytest pytest-cov

script:
  - py.test --cov=ts3py ts3py/tests/

after_success:
  - pip install coveralls
  - coveralls
